### ISSUE TITLE
Move FAQs at installation to FAQs

### ISSUE THREAD

**Issue by koppor** [JabRef/user-documentation#243]
One finds FAQs at https://github.com/JabRef/help.jabref.org/blob/gh-pages/en/Installation.md#freezes-when-running-jabref. They should be moved to the FAQ and there should be a reference to that FAQ from there.

Maybe, the whole FAQ should be checked / rewritten. Maybe, there is a good FAQ system in 2019. Maybe, we should start the FAQ at gitbooks. Refs https://github.com/JabRef/help.jabref.org/issues/178#issuecomment-541463950

**Comment by parammittal16** [comment]
@koppor  can i do it ?

**Comment by tobiasdiez** [comment]
I've now moved all installation-related FAQs to the installation instructions. There was enough space and the content fits nicely in this context. 

I think the rest of the FAQ can be integrated in the main text as well. Especially since many of these questions are actually not "frequently asked" but more "rarely asked" and thus of little value in a very long list (but could add value in a proper context). Moreover, I think google is good enough to find answers in longer texts which makes FAQ a bit useless.
