### ISSUE TITLE
Page "Cleanup entries". How to restore an older version

### ISSUE THREAD

**Issue by mlep** [JabRef/user-documentation#356]
On https://docs.jabref.org/finding-sorting-and-cleaning-entries/cleanupentries, there is at least one paragraph missing (line starting with "under the tableEnable field formatters."). 
To restore the missing text, I want to look at the file history, but  I cannot display it in the repository.

**Comment by koppor** [comment]
Fixed by https://github.com/JabRef/www.jabref.org/issues/109. Now, everything should be back to normal!

The history is currently not in a good working thing, because the GitBook/GitHub integration is not that good. (See https://github.com/JabRef/user-documentation/commits/main for the history)

I hope, that not many of your updates the last days were lost.
